[package]
name = "orbimage"
description = "Orbital image features"
repository = "https://github.com/redox-os/orbimage"
version = "0.1.4"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
orbclient = "0.1"

[dependencies.png]
version = "0.5"
optional = true
default-features = false

[features]
default = ["png"]
